# Setup
title:		Learn to Mod PE
tagline:	'blog'
description:	'My personal blog.'
url:		http://modmcpeonmac.github.io

author:
  name:		'Ian Camporez Brunelli'

---
markdown: kramdown
highlighter: pygments
relative_permalinks: false
permalink: "/news/:year/:month/:day/:title/"
excerpt_separator: ''
gauges_id: 503c5af6613f5d0f19000027
google_analytics_id: UA-50755011-1
repository: https://github.com/modmcpeonmac
# help_url: https://github.com/jekyll/jekyll-help
collections:
  docs:
    output: true
sass:
  style: compressed
